# Generated by Django 5.1 on 2024-09-26 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_hoteldetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoteldetail',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='HotelDetails/'),
        ),
    ]
