# Generated by Django 5.1 on 2024-09-26 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_hoteldetail_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.hotel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.userprofile')),
            ],
        ),
    ]
