# Generated by Django 5.1 on 2024-09-26 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0008_remove_booking_user_booking_check_in_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoteldetail',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
