# Generated by Django 5.1 on 2024-09-26 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0011_remove_booking_guest_details_alter_booking_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='check_in_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='check_out_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='num_guests',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='num_rooms',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='room_type',
        ),
    ]
