# Generated by Django 5.1 on 2024-09-27 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0013_remove_booking_email_remove_booking_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='check_in_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='booking',
            name='check_out_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(default='guest@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='booking',
            name='guest_details',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='booking',
            name='name',
            field=models.CharField(default='Guest', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='num_guests',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='num_rooms',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='phone',
            field=models.CharField(default='0000000000', max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='room_type',
            field=models.CharField(default='Standard', max_length=50),
        ),
    ]
