# Generated by Django 5.1 on 2024-09-28 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0015_remove_booking_check_in_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('days', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('after_discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('reviews', models.IntegerField()),
                ('image', models.URLField()),
            ],
        ),
    ]
