# Generated by Django 5.1 on 2024-09-28 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0017_remove_destination_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='email',
            field=models.EmailField(blank=True, default='example@gmail.com', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='image',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='destination',
            name='name',
            field=models.CharField(blank=True, default='john', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='after_discount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='destination',
            name='days',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='destination',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='destination',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='destination',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='destination',
            name='reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='destination',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
